In [1]:
pip install pandas scikit-learn joblib flask numpy

Note: you may need to restart the kernel to use updated packages.


In [1]:
import pandas as pd

In [2]:
data=pd.read_csv("FAERS_Dataset.csv")
data.head(5)

Patient ID  Age  Gender     Drug Name  Dosage (mg/day)  Duration (Months)  \
0           1   33       1   Paracetamol             1000                 60   
1           2   34       2  Atorvastatin              500                 12   
2           3   40       2    Amlodipine               20                 24   
3           4   59       2  Atorvastatin               50                 48   
4           5   61       1     Ibuprofen               40                 48   

  Chronic Conditions  Kidney Function (GFR)  Creatinine Levels (mg/dL)  \
0           Diabetes             119.742723                   1.777336   
1           Diabetes              96.147332                   1.348216   
2      Heart Disease             110.332296                   1.794065   
3       Hypertension             119.314638                   0.898335   
4      Heart Disease              88.186858                   1.254710   

   Liver Function (ALT/AST)  Blood Pressure (Systolic)  Blood Glucose (mg/dL)  \
0                        77                        134                    215   
1                        39                         94                     97   
2                        66                        115                    130   
3                        27                        175                    240   
4                        69                        177                    138   

    Side Effect  Side Effect Severity  Time to Side Effect (Months)  \
0  Heart Attack                     2                            17   
1     Blindness                     3                            30   
2    Neuropathy                     1                            58   
3     Blindness                     2                            19   
4     Blindness                     3                             4   

   Predicted Long-Term Risk  
0                  0.193193  
1                  0.203295  
2                  0.853688  
3                  0.298978  
4                  0.601920

In [3]:
data.isnull().sum()

Patient ID                         0
Age                                0
Gender                             0
Drug Name                          0
Dosage (mg/day)                    0
Duration (Months)                  0
Chronic Conditions              1226
Kidney Function (GFR)              0
Creatinine Levels (mg/dL)          0
Liver Function (ALT/AST)           0
Blood Pressure (Systolic)          0
Blood Glucose (mg/dL)              0
Side Effect                        0
Side Effect Severity               0
Time to Side Effect (Months)       0
Predicted Long-Term Risk           0
dtype: int64

In [4]:
data=data.drop(['Patient ID','Time to Side Effect (Months)','Predicted Long-Term Risk'],axis =1)


In [5]:
data

Age  Gender      Drug Name  Dosage (mg/day)  Duration (Months)  \
0      33       1    Paracetamol             1000                 60   
1      34       2   Atorvastatin              500                 12   
2      40       2     Amlodipine               20                 24   
3      59       2   Atorvastatin               50                 48   
4      61       1      Ibuprofen               40                 48   
...   ...     ...            ...              ...                ...   
4995   78       1      Metformin               50                 60   
4996   43       2  Ciprofloxacin              500                 24   
4997   80       1  Ciprofloxacin               20                  6   
4998   37       1  Ciprofloxacin               40                  6   
4999   81       2   Atorvastatin             1000                 48   

     Chronic Conditions  Kidney Function (GFR)  Creatinine Levels (mg/dL)  \
0              Diabetes             119.742723                   1.777336   
1              Diabetes              96.147332                   1.348216   
2         Heart Disease             110.332296                   1.794065   
3          Hypertension             119.314638                   0.898335   
4         Heart Disease              88.186858                   1.254710   
...                 ...                    ...                        ...   
4995           Diabetes              97.907622                   0.958974   
4996                NaN             111.924671                   1.439894   
4997                NaN              86.291324                   0.999554   
4998                NaN              37.153974                   0.613168   
4999                NaN              94.814768                   1.881445   

      Liver Function (ALT/AST)  Blood Pressure (Systolic)  \
0                           77                        134   
1                           39                         94   
2                           66                        115   
3                           27                        175   
4                           69                        177   
...                        ...                        ...   
4995                        15                        153   
4996                        54                         93   
4997                        12                        135   
4998                        23                        113   
4999                        25                        166   

      Blood Glucose (mg/dL)     Side Effect  Side Effect Severity  
0                       215    Heart Attack                     2  
1                        97       Blindness                     3  
2                       130      Neuropathy                     1  
3                       240       Blindness                     2  
4                       138       Blindness                     3  
...                     ...             ...                   ...  
4995                    149    Heart Attack                     3  
4996                    225       Blindness                     1  
4997                    208    Liver Damage                     2  
4998                    215      Neuropathy                     1  
4999                    165  Kidney Failure                     2  

[5000 rows x 13 columns]

In [6]:
from sklearn.preprocessing import LabelEncoder
encoder_drug = LabelEncoder()
encoder_condition = LabelEncoder()
encoder_effect = LabelEncoder()

In [7]:
data['Drug Name'] = encoder_drug.fit_transform(data['Drug Name'])
data['Chronic Conditions'] = encoder_condition.fit_transform(data['Chronic Conditions'])
data['Side Effect'] = encoder_effect.fit_transform(data['Side Effect'])


In [8]:
import joblib
joblib.dump(encoder_drug, "label_encoder_drug.pkl")
joblib.dump(encoder_condition, "label_encoder_condition.pkl")
joblib.dump(encoder_effect, "label_encoder_effect.pkl")
print("Encoders saved successfully!")

Encoders saved successfully!


In [9]:
data

Age  Gender  Drug Name  Dosage (mg/day)  Duration (Months)  \
0      33       1          6             1000                 60   
1      34       2          1              500                 12   
2      40       2          0               20                 24   
3      59       2          1               50                 48   
4      61       1          3               40                 48   
...   ...     ...        ...              ...                ...   
4995   78       1          5               50                 60   
4996   43       2          2              500                 24   
4997   80       1          2               20                  6   
4998   37       1          2               40                  6   
4999   81       2          1             1000                 48   

      Chronic Conditions  Kidney Function (GFR)  Creatinine Levels (mg/dL)  \
0                      0             119.742723                   1.777336   
1                      0              96.147332                   1.348216   
2                      1             110.332296                   1.794065   
3                      2             119.314638                   0.898335   
4                      1              88.186858                   1.254710   
...                  ...                    ...                        ...   
4995                   0              97.907622                   0.958974   
4996                   3             111.924671                   1.439894   
4997                   3              86.291324                   0.999554   
4998                   3              37.153974                   0.613168   
4999                   3              94.814768                   1.881445   

      Liver Function (ALT/AST)  Blood Pressure (Systolic)  \
0                           77                        134   
1                           39                         94   
2                           66                        115   
3                           27                        175   
4                           69                        177   
...                        ...                        ...   
4995                        15                        153   
4996                        54                         93   
4997                        12                        135   
4998                        23                        113   
4999                        25                        166   

      Blood Glucose (mg/dL)  Side Effect  Side Effect Severity  
0                       215            1                     2  
1                        97            0                     3  
2                       130            4                     1  
3                       240            0                     2  
4                       138            0                     3  
...                     ...          ...                   ...  
4995                    149            1                     3  
4996                    225            0                     1  
4997                    208            3                     2  
4998                    215            4                     1  
4999                    165            2                     2  

[5000 rows x 13 columns]

In [10]:
x= data.drop(columns=["Side Effect Severity"])
y = data["Side Effect Severity"]

In [11]:
x

Age  Gender  Drug Name  Dosage (mg/day)  Duration (Months)  \
0      33       1          6             1000                 60   
1      34       2          1              500                 12   
2      40       2          0               20                 24   
3      59       2          1               50                 48   
4      61       1          3               40                 48   
...   ...     ...        ...              ...                ...   
4995   78       1          5               50                 60   
4996   43       2          2              500                 24   
4997   80       1          2               20                  6   
4998   37       1          2               40                  6   
4999   81       2          1             1000                 48   

      Chronic Conditions  Kidney Function (GFR)  Creatinine Levels (mg/dL)  \
0                      0             119.742723                   1.777336   
1                      0              96.147332                   1.348216   
2                      1             110.332296                   1.794065   
3                      2             119.314638                   0.898335   
4                      1              88.186858                   1.254710   
...                  ...                    ...                        ...   
4995                   0              97.907622                   0.958974   
4996                   3             111.924671                   1.439894   
4997                   3              86.291324                   0.999554   
4998                   3              37.153974                   0.613168   
4999                   3              94.814768                   1.881445   

      Liver Function (ALT/AST)  Blood Pressure (Systolic)  \
0                           77                        134   
1                           39                         94   
2                           66                        115   
3                           27                        175   
4                           69                        177   
...                        ...                        ...   
4995                        15                        153   
4996                        54                         93   
4997                        12                        135   
4998                        23                        113   
4999                        25                        166   

      Blood Glucose (mg/dL)  Side Effect  
0                       215            1  
1                        97            0  
2                       130            4  
3                       240            0  
4                       138            0  
...                     ...          ...  
4995                    149            1  
4996                    225            0  
4997                    208            3  
4998                    215            4  
4999                    165            2  

[5000 rows x 12 columns]

In [12]:
y

0       2
1       3
2       1
3       2
4       3
       ..
4995    3
4996    1
4997    2
4998    1
4999    2
Name: Side Effect Severity, Length: 5000, dtype: int64

from imblearn.over_sampling import SMOTE
smote = SMOTE(random_state=42)
x_resampled, y_resampled = smote.fit_resample(x, y)

from collections import Counter
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.3, random_state=42)

smote = SMOTE(sampling_strategy='auto', random_state=42)
x_train_resampled, y_train_resampled = smote.fit_resample(x_train, y_train)

print("Before SMOTE:", Counter(y_train))  
print("After SMOTE:", Counter(y_train_resampled))

In [13]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, stratify=y, test_size=0.3, random_state=42)

In [14]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

In [15]:
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train, y_train)

RandomForestClassifier()

In [16]:
rf=RandomForestClassifier(random_state=42)

In [17]:
params={'n_estimators':[50,80,100],
       'max_depth':[5,7,10],
       'min_samples_split':[2,5,10],
       'min_samples_leaf':[1,2,4],
       'bootstrap':[True,False]
       }

In [18]:
from sklearn.model_selection import train_test_split, GridSearchCV, cross_val_score
grid_search=GridSearchCV(param_grid=params,estimator=rf,cv=5,scoring='accuracy',verbose=2,n_jobs=-1)

In [19]:
grid_search.fit(x_train,y_train)

Fitting 5 folds for each of 162 candidates, totalling 810 fits


GridSearchCV(cv=5, estimator=RandomForestClassifier(random_state=42), n_jobs=-1,
             param_grid={'bootstrap': [True, False], 'max_depth': [5, 7, 10],
                         'min_samples_leaf': [1, 2, 4],
                         'min_samples_split': [2, 5, 10],
                         'n_estimators': [50, 80, 100]},
             scoring='accuracy', verbose=2)

In [20]:
best_ref=grid_search.best_estimator_

In [21]:
print(grid_search.best_params_)

{'bootstrap': False, 'max_depth': 10, 'min_samples_leaf': 1, 'min_samples_split': 2, 'n_estimators': 100}


In [22]:
y_pred = model.predict(x_test)

In [23]:
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score
acc = accuracy_score(y_test, y_pred)
acc

0.608

In [24]:
y_pred=best_ref.predict(x_test)
print(confusion_matrix(y_test, y_pred))

[[268 133  95]
 [ 89 336  87]
 [ 86 108 298]]


In [25]:
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           1       0.60      0.54      0.57       496
           2       0.58      0.66      0.62       512
           3       0.62      0.61      0.61       492

    accuracy                           0.60      1500
   macro avg       0.60      0.60      0.60      1500
weighted avg       0.60      0.60      0.60      1500



In [26]:
pred1=model.predict([[34,2,1,500,12,0,96.147332,1.348216,39,94,97,0]])
pred1

array([3])

In [27]:
pred2=model.predict([[3,1,6,1000,60,0,119.742723,1.777336,77,134,215,1]])
pred2

array([3])

In [28]:
joblib.dump(best_ref, "ragmodel.pkl")

['ragmodel.pkl']

In [29]:
import sklearn
import joblib

print("scikit-learn version:", sklearn.__version__)
print("joblib version:", joblib.__version__)


scikit-learn version: 1.6.1
joblib version: 1.4.2


In [30]:
joblib.dump(scaler, "scaler.pkl")

['scaler.pkl']